version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword123
      POSTGRES_DB: app_db
    ports:
      - "5432:5432"
    volumes:
      - datos_pg:/var/lib/postgresql/data

volumes:
  datos_pg: